# Generated by Django 4.1.4 on 2022-12-27 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companyreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='of_company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
